// eslint-disable-next-line no-unused-vars
var DynamicIndexSettings = (function() {
  var settings = {
    'index.mapper.dynamic': true,
    'index.max_refresh_listeners': true,
    'index.number_of_replicas': true,
    'index.allocation.max_retries': true,
    'index.auto_expand_replicas': true,
    'index.blocks.metadata': true,
    'index.blocks.read': true,
    'index.blocks.read_only': true,
    'index.blocks.read_only_allow_delete': true,
    'index.blocks.write': true,
    'index.compound_format': true,
    'index.gc_deletes': true,
    'index.indexing.slowlog.level': true,
    'index.indexing.slowlog.reformat': true,
    'index.indexing.slowlog.source': true,
    'index.indexing.slowlog.threshold.index.debug': true,
    'index.indexing.slowlog.threshold.index.info': true,
    'index.indexing.slowlog.threshold.index.trace': true,
    'index.indexing.slowlog.threshold.index.warn': true,
    'index.mapping.depth.limit': true,
    'index.mapping.nested_fields.limit': true,
    'index.mapping.total_fields.limit': true,
    'index.max_adjacency_matrix_filters': true,
    'index.max_rescore_window': true,
    'index.max_result_window': true,
    'index.max_slices_per_scroll': true,
    'index.merge.policy.expunge_deletes_allowed': true,
    'index.merge.policy.floor_segment': true,
    'index.merge.policy.max_merge_at_once': true,
    'index.merge.policy.max_merge_at_once_explicit': true,
    'index.merge.policy.max_merged_segment': true,
    'index.merge.policy.reclaim_deletes_weight': true,
    'index.merge.policy.segments_per_tier': true,
    'index.merge.scheduler.auto_throttle': true,
    'index.merge.scheduler.max_merge_count': true,
    'index.merge.scheduler.max_thread_count': true,
    'index.optimize_auto_generated_id': true,
    'index.priority': true,
    'index.recovery.initial_shards': true,
    'index.refresh_interval': true,
    'index.requests.cache.enable': true,
    'index.routing.allocation.enable': true,
    'index.routing.allocation.total_shards_per_node': true,
    'index.routing.rebalance.enable': true,
    'index.search.slowlog.level': true,
    'index.search.slowlog.threshold.fetch.debug': true,
    'index.search.slowlog.threshold.fetch.info': true,
    'index.search.slowlog.threshold.fetch.trace': true,
    'index.search.slowlog.threshold.fetch.warn': true,
    'index.search.slowlog.threshold.query.debug': true,
    'index.search.slowlog.threshold.query.info': true,
    'index.search.slowlog.threshold.query.trace': true,
    'index.search.slowlog.threshold.query.warn': true,
    'index.shared_filesystem.recover_on_any_node': true,
    'index.store.throttle.max_bytes_per_sec': true,
    'index.store.throttle.type': true,
    'index.translog.durability': true,
    'index.translog.flush_threshold_size': true,
    'index.ttl.disable_purge': true,
    'index.unassigned.node_left.delayed_timeout': true,
    'index.warmer.enabled': true,
    'index.write.wait_for_active_shards': true,
  };

  return {
    valid: function(setting) {
      return settings[setting] || false;
    },
  };
})();

